### PR TITLE
update readme to fit dependencies

### PR DESCRIPTION
**Pull request by tryadelion**

### CODE REVIEW

**Comment by natario1** [comment]
Thanks man! But actually, the only think that's needed is jcenter(), and that's enabled by default in Studio projects. I think this adds confusion then

**Comment by tryadelion** [comment]
it's not enabled by default on all projects, i had to google it for your lib to work.

**Comment by natario1** [comment]
Fine then! Can you remove the other two providers, and specify that your lines must be added to the project's Gradle file?

**Comment by tryadelion** [comment]
yup, will do and re-do a PR.

**Pull request closed without merging**
