### PR TITLE
Wrapped some crashes happened when start camera

### PR DESCRIPTION
**Pull request by Namazed**
- Fixes: #850
- Tests: no
- Docs updated: no

### Solution
I wrapped in tryCatch these problem places.

### CODE REVIEW

**Comment by natario1** [comment]
Thanks @Namazed ! I'll merge when CI is over and do a new release.

**Comment by EverydayPineapple** [comment]
Hi @natario1 - was wondering if you were still planning on making a release soon? I'd love to start using the library in my project but am waiting on a release before I can.

**Comment by natario1** [comment]
@EverydayPineapple sorry if you got stuck - you can always use jitpack.io to depend on specific branches of this library (or your own fork). This way you don't have to wait for the official releases, which I will do eventually, but it can only happen in my free time.

**Comment by EverydayPineapple** [comment]
No problems - wasn't too stuck so was happy to wait. Thanks for the advice though will use that in future.

**Pull request merged**
