### PR TITLE
Reduced memory usage to avoid any OOM.

### PR DESCRIPTION
**Pull request by RobertoMorelos**
# Implements
https://github.com/natario1/CameraView/issues/91

# Description
Reduced memory usage to avoid any OOM.

## Before
Library could lead to OOM due to the huge amount of memory allocated by the bitmap.
no_improvement
(Java memory increases up to 60 MB, sometimes up to 100 MB!)

## After
Memory usage reduced and released the bitmap memory allocated.
improvement
(Java memory increases from 17 MB to 25 MB only)

## Reviewers
See reviewer section.

### CODE REVIEW

**Comment by natario1** [comment]
This is a bit confusing. I think that `crop.recycle()` is needed and should help.

But in `CameraUtils` by using halfWidth and halfHeight instead of width and height, you are loading a **bigger** image, not smaller. Also with `||` instead of `&&`, you are just making it bigger. This can only increase the memory, right?

I think all the benefit you are seeing is just due to crop.recycle().

**Comment by RobertoMorelos** [comment]
I tried it just with `crop.recycle()` and I did not see any difference in performance. What I changed is based on the developers page `(https://developer.android.com/topic/performance/graphics/load-bitmap.html)`.
Basically you need the largest sample size value, but you need the `&&` to keep width and height, otherwise you'll get the largest but only in one side (either width or height).

**Comment by natario1** [comment]
I understand what you say, but the developer page is wrong in this, it's the opposite. You can try yourself, see `CameraUtilsTest#testDecodeDownscaledBitmap`. In your case the final bitmap is bigger than the given `maxWidth` and `maxHeight`, so the test fails (see travis logs).

I know this because I have worked on this recently. I honestly don't understand the developer page example...

I'd say, let's merge just the recycle call for now

**Comment by RobertoMorelos** [comment]
I disagree, with just the `crop.recycle()` we get this result:
screen recording 2017-11-02 at 01 22 pm

Maybe the test is only measuring the width and height, but no the memory allocated (the actual bitmap size).

**Comment by natario1** [comment]
I don't how to explain your results, different shoot orientations, the code you are running, some obscure native cache, I don't know. I'm getting good results so I think you should just pass a lower value of `maxWidth` and `maxHeight` when loading the bitmap in your own activity view.

Since we are trying to reduce memory here, loading bigger bitmaps in the library code is not a good idea :) recycle() will not solve the main issue, but it's needed. If you can go back to just that, we can merge this

**Comment by RobertoMorelos** [comment]
Ok, I understand what you are saying. I always did the same test case: take a picture with `cameraCropOutput` enabled in portrait mode. I always called the garbage collector before doing my tests so no any other memory allocation could change the results. If you want me to just add the `crop.recycle()` it's fine, but I hope no memory issues come to the near feature.

**Comment by natario1** [comment]
The real issue is [here](https://github.com/natario1/CameraView/blob/f3317ad4eedac34f16f19a4b10c6e7199fd1f889/cameraview/src/main/utils/com/otaliastudios/cameraview/CropHelper.java#L24) and it is [not affected](https://github.com/natario1/CameraView/blob/f3317ad4eedac34f16f19a4b10c6e7199fd1f889/cameraview/src/main/utils/com/otaliastudios/cameraview/CameraUtils.java#L152) by your changes because it uses `Integer.MAX_VALUE`. I'll see if I can find a workaround. Meanwhile, yes, I think we should merge the recycle call! I really can't explain your profiles right now...

**Comment by RobertoMorelos** [comment]
@natario1 Done! Thank you!

**Comment by natario1** [comment]
@RobertoMorelos thanks a lot for your time.

**Pull request merged**
