### PR TITLE
Handle autoFocus exceptions (issue #181)

### PR DESCRIPTION
**Pull request by mahdi-ninja**
Fix for [autoFocus failed in tablets #181](https://github.com/natario1/CameraView/issues/181)

The tldr version is that some devices (including Galaxy Tab A 7.0" 2016 and lots of Sony phones like Xperia Z, Z1, V, ...) occasionally throw Runtime exceptions when calling autoFocus.
It doesn't seem that we can do much about. So, let's at least handle the exception and prevent the crash and user can trigger the focus later if required.

### CODE REVIEW

**Comment by mahdi-ninja** [comment]
@wosiu There are a couple of issues with that specific implementation. First, we should add a counter and limit the number of retries. Second, we shouldn't run the scheduled `autoFocus` call, if user has already asked for a focus on a different part of the picture.

**Comment by mahdi-ninja** [comment]
If we want to be fancy, maybe we can add a callback for failed focus (or failed things in general) and let the developers decide if and how they want to handle this.

**Comment by natario1** [comment]
Thank you @mahdi-ninja, I'm sorry for delaying this. Looks good to me, but could you call dispatchOnFocusEnd (with success = false) in the catch block?

And use the camera logger LOG instead of android Log.

**Comment by mahdi-ninja** [comment]
Thanks @natario1 for the review. I have updated the code.

**Comment by natario1** [comment]
Can you sync with master? Then we're ready to merge

**Comment by mahdi-ninja** [comment]
@natario1  Should be good now

**Comment by natario1** [comment]
Thanks! I will release a new version once we merge a couple other PRs

**Pull request merged**
